### ISSUE TITLE
PipeSecurity support?

### ISSUE THREAD

**Issue by andrewpros** [seaeagle1/EasyPipes#2]
Cannot use with UWP without PipeSecurity support.

**Comment by seaeagle1** [comment]
Aren't UWP apps sandboxed, which would preclude IPC?

Anyway, I believe PipeSecurity is not in the .NET Standard API. You could override the Client.Connect and Server.ReceiveAction methods though, to provide your own pipes.

**Comment by andrewpros** [comment]
UWP is sandboxed, but is allowing multiple types of communication under some requirements, one of them is IPC, but it is available only recently and best to be used on win10 2004+, but it requires to setup the server pipe with proper PipeSecurity rules or else uwp will not allow it to connect to the pipe, client doesn't need such thing.
Although uwp can both be the server and client ipc it is easier to use it as client and setup the server in a .net or .net core app.
Anyway, PipeSecurity is not only needed for uwp, its part of the IPC possibilities so either way it would be nice to have it out of the box.
But yeah, is see the methods are virtual, so it is some way to deal with it.

**Comment by seaeagle1** [comment]
Added custom constructor support to Server to allow use of the PipeSecurity-supporting functions without breaking the .NET Standard requirement. See af44c4b570b5079cb074ca6c8ffe10e595b480c5 .

**Comment by andrewpros** [comment]
Thx
